# Generated by Django 5.1.7 on 2025-04-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
