# Generated by Django 5.1.7 on 2025-04-10 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_cuisine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
