# Generated by Django 5.1.7 on 2025-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='receipts/'),
        ),
    ]
