# Generated by Django 5.1.7 on 2025-04-07 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_total_amount_orderitem_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.ManyToManyField(related_name='foods', to='api.menu'),
        ),
        migrations.AddField(
            model_name='food',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(default='9 AM - 11 PM', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('UPI', 'UPI'), ('Wallet', 'Wallet')], default='Cash', max_length=50),
        ),
    ]
