# Generated by Django 5.1.7 on 2025-04-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_table_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
