# Generated by Django 5.1.7 on 2025-04-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_payment_user_alter_order_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='menu',
            new_name='menus',
        ),
    ]
