# Generated by Django 5.1.7 on 2025-04-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_orderitem_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(default=None, related_name='orders', through='api.OrderItem', to='api.food'),
        ),
    ]
