# Generated by Django 5.1.7 on 2025-04-18 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
