# Generated by Django 5.1.7 on 2025-04-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
