# Generated by Django 5.1.7 on 2025-04-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_table_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='table-qrcodes/'),
        ),
    ]
